// Copyright 2022 beekeeb
// SPDX-License-Identifier: GPL-2.0-or-later

#include QMK_KEYBOARD_H
#include "g/keymap_combo.h"


#define _LAYER0 0
#define _LAYER1 1
#define _LAYER2 2
#define _LAYER3 3
#define _LAYER4 4
#define _LAYER5 5
#define _LAYER6 6

enum custom_keycodes {
    LAYER0,
    LAYER1,
    LAYER2,
    LAYER3,
    LAYER4,
    LAYER5,
    LAYER6,
};

 const uint16_t PROGMEM keymaps[][MATRIX_ROWS][MATRIX_COLS] = {
[_LAYER0] = LAYOUT_split_3x6_3(KC_NO, KC_Q, KC_W, KC_E, KC_R, KC_T, KC_Y, KC_U, KC_I, KC_O, KC_P, KC_NO, KC_NO, LSFT_T(KC_A), KC_S, KC_D, KC_F, LGUI_T(KC_G), LGUI_T(KC_H), KC_J, KC_K, KC_L, LSFT_T(KC_MINS), KC_NO, KC_NO, LCTL_T(KC_PEQL), LALT_T(KC_Z), KC_X, KC_C, KC_V, KC_B, KC_N, KC_M, KC_COMM, LCTL_T(KC_DOT), KC_NO, KC_NO, LT(1,KC_TAB), LT(2,KC_SPC), LT(3,KC_ENT), KC_BSPC, KC_NO),
[_LAYER1] = LAYOUT_split_3x6_3(KC_NO, KC_NO, KC_NO, KC_VOLD, KC_MUTE, KC_VOLU, KC_ASTR, RALT(KC_7), RALT(KC_NUBS), RALT(KC_0), KC_LPRN, KC_NO, KC_NO, KC_LSFT, KC_NO, KC_NO, KC_NO, KC_LGUI, KC_LEFT, KC_DOWN, KC_UP, KC_RGHT, RALT(KC_MINS), KC_NO, KC_NO, KC_LCTL, KC_NO, KC_NO, KC_BRID, KC_BRIU, RALT(KC_8), KC_NUBS, KC_NUHS, LSFT(KC_NUBS), RALT(KC_9), KC_NO, KC_NO, KC_TAB, KC_SPC, KC_ENT, KC_BSPC, KC_NO),
[_LAYER2] = LAYOUT_split_3x6_3(KC_NO, KC_F1, KC_F2, KC_F3, KC_F4, KC_F5, KC_1, KC_2, KC_3, KC_0, KC_LBRC, KC_NO, KC_NO, KC_LSFT, KC_NO, KC_NO, LCTL(KC_A), KC_LGUI, KC_4, KC_5, KC_6, KC_RCBR, KC_SCLN, KC_NO, KC_NO, KC_LCTL, KC_F6, KC_F7, KC_F8, KC_F9, KC_7, KC_8, KC_9, KC_INT1, KC_QUOT, KC_NO, KC_NO, KC_TAB, KC_SPC, KC_ENT, KC_BSPC, KC_NO),
[_LAYER3] = LAYOUT_split_3x6_3(KC_NO, RALT(KC_Q), KC_PIPE, KC_AT, KC_DLR, KC_CIRC, TO(4), KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_GRV, KC_EQL, KC_QUES, KC_RBRC, KC_PERC, KC_LGUI, KC_NO, KC_NO, KC_NO, KC_LSFT, KC_NO, KC_NO, RALT(KC_RBRC), KC_HASH, KC_AMPR, KC_SLSH, KC_EXLM, KC_NO, KC_NO, KC_NO, KC_NO, KC_LCTL, KC_NO, KC_NO, KC_TAB, KC_SPC, KC_ENT, KC_BSPC, KC_NO),
[_LAYER4] = LAYOUT_split_3x6_3(KC_NO, KC_TAB, KC_Q, KC_W, KC_E, KC_R, KC_TAB, KC_F1, KC_F2, KC_F3, KC_NO, KC_NO, KC_NO, KC_LSFT, KC_A, KC_S, KC_D, KC_F, KC_LEFT, KC_DOWN, KC_UP, KC_RGHT, KC_NO, KC_NO, KC_NO, KC_LCTL, KC_Z, KC_X, KC_C, KC_G, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, MO(5), KC_SPC, KC_ENT, TO(0), KC_NO),
[_LAYER5] = LAYOUT_split_3x6_3(KC_NO, KC_1, KC_2, KC_W, KC_3, KC_4, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_LSFT, KC_A, KC_S, KC_D, KC_5, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_LCTL, KC_B, KC_N, KC_M, KC_6, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_SPC, KC_NO, KC_NO, KC_NO),
[_LAYER6] = LAYOUT_split_3x6_3(KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_TRNS, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO)
};
